In [125]:
import pandas as pd
import numpy as np
import matplotlib as plot
import csv
import openpyxl
from datetime import datetime

In [54]:
weekend_movie_gross_excel = pd.read_excel(r"C:\Users\mattl\code\SavvyCoders\Capstone\Data Sets\Opening Weekend Gross.xlsx")

In [56]:
weekend_movie_gross_excel

,Release,Opening,Total Gross,% of Total,Theaters,Average,Date,Distributor
0,Avengers: Endgame,357115007.0,858373000.0,0.416,4662.0,76601.0,2019-04-26,Walt Disney Studios Motion Pictures
1,Spider-Man: No Way Home,260138569.0,804793477.0,0.323,4336.0,59995.0,2021-12-17,Sony Pictures Entertainment (SPE)
2,Avengers: Infinity War,257698183.0,678815482.0,0.380,4474.0,57599.0,2018-04-27,Walt Disney Studios Motion Pictures
3,Star Wars: Episode VII - The Force Awakens,247966675.0,936662225.0,0.265,4134.0,59982.0,2015-12-18,Walt Disney Studios Motion Pictures
4,Star Wars: Episode VIII - The Last Jedi,220009584.0,620181382.0,0.355,4232.0,51987.0,2017-12-15,Walt Disney Studios Motion Pictures
...,...,...,...,...,...,...,...,...
995,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,21234994.0,49505008.0,0.429,1614.0,13156.0,2021-04-23,FUNimation Entertainment
996,Boo 2! A Madea Halloween,21226953.0,47319572.0,0.449,2388.0,8889.0,2017-10-20,Lions Gate Films
997,Payback,21221526.0,81526121.0,0.260,2729.0,7776.0,1999-02-05,Paramount Pictures
998,Four Brothers,21176925.0,74494381.0,0.284,2533.0,8360.0,2005-08-12,Paramount Pictures
999,Waterworld,21171780.0,88246220.0,0.240,2268.0,9335.0,1995-07-28,Universal Pictures

In [57]:
weekend_movie_gross_excel ['Date'].value_counts()

Date
2012-02-10    4
2017-02-10    3
2004-06-11    3
2016-07-22    3
2016-06-10    3
             ..
1992-06-19    1
1996-05-22    1
2018-08-10    1
2001-08-10    1
1995-07-28    1
Name: count, Length: 859, dtype: int64

In [116]:
weekend_movie_gross_excel.drop(['% of Total', 'Theaters', 'Average'], axis=1, inplace=True)

KeyError: "['% of Total', 'Theaters', 'Average'] not found in axis"

In [59]:
weekend_movie_gross_excel

,Release,Opening,Total Gross,Date,Distributor
0,Avengers: Endgame,357115007.0,858373000.0,2019-04-26,Walt Disney Studios Motion Pictures
1,Spider-Man: No Way Home,260138569.0,804793477.0,2021-12-17,Sony Pictures Entertainment (SPE)
2,Avengers: Infinity War,257698183.0,678815482.0,2018-04-27,Walt Disney Studios Motion Pictures
3,Star Wars: Episode VII - The Force Awakens,247966675.0,936662225.0,2015-12-18,Walt Disney Studios Motion Pictures
4,Star Wars: Episode VIII - The Last Jedi,220009584.0,620181382.0,2017-12-15,Walt Disney Studios Motion Pictures
...,...,...,...,...,...
995,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,21234994.0,49505008.0,2021-04-23,FUNimation Entertainment
996,Boo 2! A Madea Halloween,21226953.0,47319572.0,2017-10-20,Lions Gate Films
997,Payback,21221526.0,81526121.0,1999-02-05,Paramount Pictures
998,Four Brothers,21176925.0,74494381.0,2005-08-12,Paramount Pictures
999,Waterworld,21171780.0,88246220.0,1995-07-28,Universal Pictures

In [65]:
weekend_movie_gross_excel.sort_values(by = ['Date'], inplace=True, ascending=False)

In [66]:
weekend_movie_gross_excel

,Release,Opening,Total Gross,Date,Distributor
955,Renaissance: A Film by BeyoncÃ©,21801216.0,21801216.0,2023-12-01,-
337,The Hunger Games: The Ballad of Songbirds & Sn...,44607143.0,125099432.0,2023-11-17,Lions Gate Films
627,Trolls Band Together,30002525.0,76474100.0,2023-11-17,Universal Pictures
322,The Marvels,46110859.0,81419870.0,2023-11-10,Walt Disney Studios Motion Pictures
116,Five Nights at Freddy's,80001720.0,137038110.0,2023-10-27,Universal Pictures International (UPI)
...,...,...,...,...,...
642,Indiana Jones and the Last Crusade,29355021.0,197171806.0,1989-05-24,Paramount Pictures
738,Beverly Hills Cop II,26348555.0,153665036.0,1987-05-20,Paramount Pictures
774,Indiana Jones and the Temple of Doom,25337110.0,179870271.0,1984-05-23,Paramount Pictures
889,Star Wars: Episode VI - Return of the Jedi,23019618.0,252583617.0,1983-05-25,Twentieth Century Fox
469,1997 Special Edition,NaN,NaN,NaT,NaN

In [81]:
startDate = pd.to_datetime('2014-01-01')
endDate = pd.to_datetime('2019-12-31')
filterDates = weekend_movie_gross_excel[(weekend_movie_gross_excel['Date'] >= startDate) & (weekend_movie_gross_excel['Date'] <= endDate)]
filterDates

,Release,Opening,Total Gross,Date,Distributor
14,Star Wars: Episode IX - The Rise of Skywalker,177383864.0,515202542.0,2019-12-20,Walt Disney Studios Motion Pictures
205,Jumanji: The Next Level,59251543.0,320314960.0,2019-12-13,Sony Pictures Entertainment (SPE)
721,Knives Out,26769548.0,165363234.0,2019-11-27,Lions Gate Films
42,Frozen II,130263358.0,477373578.0,2019-11-22,Walt Disney Studios Motion Pictures
567,Ford v Ferrari,31474958.0,117624357.0,2019-11-15,Twentieth Century Fox
...,...,...,...,...,...
758,About Last Night,25649011.0,48637684.0,2014-02-14,Screen Gems
968,RoboCop,21681430.0,58607007.0,2014-02-12,Sony Pictures Entertainment (SPE)
945,The Monuments Men,22003433.0,78031620.0,2014-02-07,Sony Pictures Entertainment (SPE)
154,The Lego Movie,69050279.0,257760692.0,2014-02-07,Warner Bros.
373,Ride Along,41516170.0,134938200.0,2014-01-17,Universal Pictures

In [83]:
csv_file_path = r'C:\Users\mattl\code\SavvyCoders\Capstone\Data Sets\FirstWeekendData.csv'

# Save the DataFrame to a CSV file
filterDates.to_csv(csv_file_path, index=False)

print(f"DataFrame saved to {csv_file_path}")

DataFrame saved to C:\Users\mattl\code\SavvyCoders\Capstone\Data Sets\FirstWeekendData.csv

In [119]:
movie_data = pd.read_csv(r"C:\Users\mattl\code\SavvyCoders\Capstone\Data Sets\Cumulative Movie Data.csv")
substring = '('
# string_data = movie_data['released'].str.split(substring).str.get(0).str.strip()
movie_data['Cleaned_released_date'] = movie_data['released'].str.split(substring).str.get(0).str.strip()
# date_object = datetime.strptime(str(string_data), "%B %d, %Y")
# movie_data['Clean_Release_Date'] = string_data
movie_data

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Cleaned_released_date
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,"June 13, 1980"
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,"July 2, 1980"
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,"June 20, 1980"
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,"July 2, 1980"
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,"July 25, 1980"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0,"October 23, 2020"
7664,Dream Round,NaN,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0,"February 7, 2020"
7665,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN,"April 27, 2020"
7666,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0,"October 1, 2020"
7667,Tee em el,NaN,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0,"August 19, 2020"

In [120]:
movie_data

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,Cleaned_released_date
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,"June 13, 1980"
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,"July 2, 1980"
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,"June 20, 1980"
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,"July 2, 1980"
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,"July 25, 1980"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0,"October 23, 2020"
7664,Dream Round,NaN,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0,"February 7, 2020"
7665,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN,"April 27, 2020"
7666,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0,"October 1, 2020"
7667,Tee em el,NaN,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0,"August 19, 2020"

In [122]:
movie_data.drop(['rating', 'score', 'votes', 'director', 'writer', 'star', 'country', 'budget', 'company', 'runtime', 'released'], axis=1, inplace=True)

In [123]:
movie_data

,name,genre,year,gross,Cleaned_released_date
0,The Shining,Drama,1980,46998772.0,"June 13, 1980"
1,The Blue Lagoon,Adventure,1980,58853106.0,"July 2, 1980"
2,Star Wars: Episode V - The Empire Strikes Back,Action,1980,538375067.0,"June 20, 1980"
3,Airplane!,Comedy,1980,83453539.0,"July 2, 1980"
4,Caddyshack,Comedy,1980,39846344.0,"July 25, 1980"
...,...,...,...,...,...
7663,More to Life,Drama,2020,NaN,"October 23, 2020"
7664,Dream Round,Comedy,2020,NaN,"February 7, 2020"
7665,Saving Mbango,Drama,2020,NaN,"April 27, 2020"
7666,It's Just Us,Drama,2020,NaN,"October 1, 2020"
7667,Tee em el,Horror,2020,NaN,"August 19, 2020"

In [5]:
defined_date = Cleaned_released_date.datetime.strptime('June 13, 1980', '%m %d, %Y')
# correct_date = Cleaned_released_date.date.strftime("%Y/%m/%d")

NameError: name 'Cleaned_released_date' is not defined

In [128]:
startDate = pd.to_datetime('January 1, 2014')
endDate = pd.to_datetime('December 31, 2019')
all_movies = movie_data[(movie_data['Cleaned_released_date'] >= startDate) & (movie_data['Cleaned_released_date'] <= endDate)]

TypeError: '>=' not supported between instances of 'str' and 'Timestamp'